import { db, categoriesTable, productsTable } from "@workspace/db";
import { eq } from "drizzle-orm";

async function run() {
  console.log("Starting trendy product insertion...");

  // 1. Ensure categories exist
  const categories = [
    { name: "T-Shirts", slug: "t-shirts", description: "Custom printed t-shirts for all occasions" },
    { name: "Hoodies", slug: "hoodies", description: "Premium quality hoodies with custom designs" },
    { name: "Mugs", slug: "mugs", description: "Personalized mugs perfect for gifts" },
    { name: "Caps", slug: "caps", description: "Stylish caps with custom embroidery" },
    { name: "Long Sleeves", slug: "long-sleeves", description: "Premium long sleeve shirts with custom designs" },
    { name: "Water Bottles", slug: "water-bottles", description: "Durable aluminum water bottles with custom prints" },
    { name: "Custom Orders", slug: "custom-orders", description: "Special custom orders tailored to your needs" },
  ];

  const catMap: Record<string, number> = {};
  for (const cat of categories) {
    let existing = await db.select().from(categoriesTable).where(eq(categoriesTable.slug, cat.slug));
    if (existing.length === 0) {
      const [inserted] = await db.insert(categoriesTable).values(cat).returning();
      catMap[cat.slug] = inserted.id;
      console.log(`Created category: ${cat.name}`);
    } else {
      catMap[cat.slug] = existing[0].id;
    }
  }

  // 2. Define trendy products
  const products = [
    // T-Shirts
    {
      name: "Birthday Celebration Tee",
      slug: "birthday-celebration-tee",
      description: "Celebrate in style with our vibrant 'Happy Birthday' typography T-shirt. Made from 100% premium cotton, it's the perfect gift for your special day.",
      price: "699",
      discountPrice: "599",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_birthday.png",
      featured: true,
      customizable: true,
      tags: ["birthday", "celebration", "gift"],
    },
    {
      name: "Apology Kitten Tee",
      slug: "apology-kitten-tee",
      description: "Say 'I'm Sorry' with this adorable sad kitten illustration. A soft and comfortable way to mend any relationship.",
      price: "699",
      discountPrice: "599",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_sorry.png",
      featured: false,
      customizable: true,
      tags: ["sorry", "cute", "gift"],
    },
    {
      name: "Keep Going Motivational Tee",
      slug: "keep-going-motivational-tee",
      description: "Stay inspired with our minimalist 'Keep Going' T-shirt. Elegant white typography on a premium navy blue base.",
      price: "699",
      discountPrice: "599",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_motivational.png",
      featured: true,
      customizable: true,
      tags: ["motivational", "minimalist", "inspiration"],
    },
    {
      name: "Viral Meme Culture Tee",
      slug: "viral-meme-culture-tee",
      description: "Wear the internet's favorite moments. This trendy T-shirt features a viral meme illustration that's sure to start conversations.",
      price: "750",
      discountPrice: "649",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_meme.png",
      featured: true,
      customizable: true,
      tags: ["meme", "trendy", "viral"],
    },
    {
      name: "Minimalist Face Line Art Tee",
      slug: "minimalist-face-line-art-tee",
      description: "A touch of modern art for your wardrobe. Features a continuous line drawing of a human face for a sophisticated, artistic look.",
      price: "750",
      discountPrice: "649",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_lineart.png",
      featured: false,
      customizable: true,
      tags: ["art", "minimalist", "lineart"],
    },
    // Hoodies
    {
      name: "Urban Explorer Streetwear Hoodie",
      slug: "urban-explorer-streetwear-hoodie",
      description: "Dominate the streets with our 'Urban Explorer' graffiti-style hoodie. Premium fleece for maximum warmth and style.",
      price: "1599",
      discountPrice: "1399",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_streetwear.png",
      featured: true,
      customizable: true,
      tags: ["streetwear", "graffiti", "urban"],
    },
    {
      name: "Cozy Winter Wishes Hoodie",
      slug: "cozy-winter-wishes-hoodie",
      description: "Stay warm this winter with our 'Winter Wishes' snowflake design. Soft fleece and a cozy fit for those chilly nights.",
      price: "1599",
      discountPrice: "1399",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_winter.png",
      featured: true,
      customizable: true,
      tags: ["winter", "cozy", "snowflake"],
    },
    {
      name: "Pro Gamer Neon Hoodie",
      slug: "pro-gamer-neon-hoodie",
      description: "Level up your style with our 'Pro Gamer' neon controller design. Perfect for long gaming sessions and late-night streams.",
      price: "1699",
      discountPrice: "1499",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_gaming.png",
      featured: true,
      customizable: true,
      tags: ["gaming", "neon", "pro"],
    },
    {
      name: "Aesthetic Anime Girl Hoodie",
      slug: "aesthetic-anime-girl-hoodie",
      description: "A minimalist anime-inspired design for the modern fan. Clean lines and a sleek aesthetic on a premium white hoodie.",
      price: "1699",
      discountPrice: "1499",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_anime.png",
      featured: false,
      customizable: true,
      tags: ["anime", "aesthetic", "minimalist"],
    },
    {
      name: "Stay Wild Nature Hoodie",
      slug: "stay-wild-nature-hoodie",
      description: "Connect with the outdoors. Our 'Stay Wild' hoodie features nature-inspired typography on a deep forest green base.",
      price: "1599",
      discountPrice: "1399",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_quote.png",
      featured: false,
      customizable: true,
      tags: ["nature", "wild", "outdoors"],
    },
    // Mugs
    {
      name: "Morning Coffee Magic Mug",
      slug: "morning-coffee-magic-mug",
      description: "Start your day with a touch of magic. This heat-sensitive mug reveals a beautiful sunrise design when filled with hot liquid.",
      price: "499",
      discountPrice: "399",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_coffee.png",
      featured: true,
      customizable: true,
      tags: ["coffee", "magic", "morning"],
    },
    {
      name: "Best Boss Ever Mug",
      slug: "best-boss-ever-mug",
      description: "The classic office favorite. High-quality ceramic mug with bold 'Best Boss Ever' typography. A perfect gift for your mentor.",
      price: "450",
      discountPrice: "349",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_boss.png",
      featured: false,
      customizable: true,
      tags: ["boss", "office", "gift"],
    },
    {
      name: "Cute Cat Lover Mug",
      slug: "cute-cat-lover-mug",
      description: "For the feline enthusiasts. Features a whimsical cat illustration and a 'Purr-fect Morning' message.",
      price: "450",
      discountPrice: "349",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_cat.png",
      featured: true,
      customizable: true,
      tags: ["cat", "cute", "pet"],
    },
    {
      name: "Gaming Over Mug",
      slug: "gaming-over-mug",
      description: "The ultimate mug for gamers. Features a retro 'Game Over' pixel art design and a controller-shaped handle.",
      price: "550",
      discountPrice: "449",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_gameover.png",
      featured: true,
      customizable: true,
      tags: ["gaming", "retro", "pixel"],
    },
    {
      name: "Inspirational Dream Mug",
      slug: "inspirational-dream-mug",
      description: "Chase your dreams with every sip. Elegant gold foil lettering on a matte black ceramic base.",
      price: "550",
      discountPrice: "449",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_dream.png",
      featured: false,
      customizable: true,
      tags: ["inspiration", "dream", "elegant"],
    },
    // Caps
    {
      name: "Classic Streetwear Snapback",
      slug: "classic-streetwear-snapback",
      description: "A staple for any streetwear collection. Premium 6-panel snapback with a clean, minimalist design.",
      price: "850",
      discountPrice: "699",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_street.png",
      featured: true,
      customizable: true,
      tags: ["streetwear", "snapback", "classic"],
    },
    {
      name: "Retro 90s Dad Hat",
      slug: "retro-90s-dad-hat",
      description: "Bring back the 90s vibe with this washed cotton dad hat. Comfortable, stylish, and perfectly vintage.",
      price: "750",
      discountPrice: "599",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_retro.png",
      featured: true,
      customizable: true,
      tags: ["retro", "dadhat", "vintage"],
    },
    {
      name: "Performance Sports Cap",
      slug: "performance-sports-cap",
      description: "Designed for athletes. Moisture-wicking fabric and a breathable mesh back to keep you cool during intense workouts.",
      price: "950",
      discountPrice: "799",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_sports.png",
      featured: false,
      customizable: true,
      tags: ["sports", "performance", "fitness"],
    },
    {
      name: "Urban Graffiti Trucker Hat",
      slug: "urban-graffiti-trucker-hat",
      description: "Make a statement with our 'Urban Graffiti' trucker hat. Features a vibrant, hand-drawn graffiti design on the front panel.",
      price: "850",
      discountPrice: "699",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_logo.png",
      featured: true,
      customizable: true,
      tags: ["urban", "graffiti", "trucker"],
    },
    {
      name: "Minimalist Initial Cap",
      slug: "minimalist-initial-cap",
      description: "Personalize your look. Features a single, elegantly embroidered initial of your choice on a premium cotton base.",
      price: "850",
      discountPrice: "699",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_initial.png",
      featured: false,
      customizable: true,
      tags: ["minimalist", "initial", "personalized"],
    },
    // Long Sleeves
    {
      name: "Modern Geometric Long Sleeve",
      slug: "modern-geometric-long-sleeve",
      description: "A sophisticated geometric pattern for the modern individual. Soft, breathable fabric for all-day comfort.",
      price: "899",
      discountPrice: "749",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_artistic.png",
      featured: true,
      customizable: true,
      tags: ["modern", "geometric", "abstract"],
    },
    {
      name: "Vintage Travel Long Sleeve",
      slug: "vintage-travel-long-sleeve",
      description: "For the wanderlust at heart. Features a beautiful vintage-style travel illustration of the Himalayas.",
      price: "899",
      discountPrice: "749",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_retro.png",
      featured: true,
      customizable: true,
      tags: ["travel", "vintage", "wanderlust"],
    },
    {
      name: "Artistic Floral Long Sleeve",
      slug: "artistic-floral-long-sleeve",
      description: "A touch of nature for your wardrobe. Features a hand-painted floral design on a premium cream base.",
      price: "950",
      discountPrice: "799",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_floral.png",
      featured: false,
      customizable: true,
      tags: ["floral", "artistic", "nature"],
    },
    {
      name: "Cyberpunk Future Long Sleeve",
      slug: "cyberpunk-future-long-sleeve",
      description: "Step into the future with our cyberpunk-inspired design. Neon accents and tech-focused typography.",
      price: "999",
      discountPrice: "849",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_space.png",
      featured: true,
      customizable: true,
      tags: ["cyberpunk", "future", "neon"],
    },
    {
      name: "Minimalist Corporate Long Sleeve",
      slug: "minimalist-corporate-long-sleeve",
      description: "The perfect choice for a professional yet casual look. Clean lines and a subtle brand logo on the chest.",
      price: "899",
      discountPrice: "749",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_corporate.png",
      featured: false,
      customizable: true,
      tags: ["corporate", "minimalist", "professional"],
    },
    // Water Bottles
    {
      name: "Eco-Friendly Bamboo Water Bottle",
      slug: "eco-friendly-bamboo-water-bottle",
      description: "Sustainable and stylish. Stainless steel bottle with a real bamboo outer layer. Keeps drinks cold for 24 hours.",
      price: "1250",
      discountPrice: "999",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_eco.png",
      featured: true,
      customizable: true,
      tags: ["eco", "bamboo", "sustainable"],
    },
    {
      name: "Pro Fitness Tracker Bottle",
      slug: "pro-fitness-tracker-bottle",
      description: "Stay hydrated and track your progress. Features time markers to remind you to drink water throughout the day.",
      price: "850",
      discountPrice: "699",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_tracker.png",
      featured: true,
      customizable: true,
      tags: ["fitness", "tracker", "health"],
    },
    {
      name: "Adventure Series Flask",
      slug: "adventure-series-flask",
      description: "Built for the rugged outdoors. Heavy-duty vacuum insulated flask with a durable powder-coated finish.",
      price: "1450",
      discountPrice: "1199",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_adventure.png",
      featured: false,
      customizable: true,
      tags: ["adventure", "flask", "outdoor"],
    },
    {
      name: "Galaxy Space Water Bottle",
      slug: "galaxy-space-water-bottle",
      description: "A stellar design for your daily hydration. Features a high-resolution nebula print and a metallic finish.",
      price: "950",
      discountPrice: "799",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_space.png",
      featured: true,
      customizable: true,
      tags: ["space", "galaxy", "nebula"],
    },
    {
      name: "Minimalist Name Bottle",
      slug: "minimalist-name-bottle",
      description: "Your bottle, your name. Features a sleek, laser-engraved name of your choice on a matte white base.",
      price: "950",
      discountPrice: "799",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_name.png",
      featured: false,
      customizable: true,
      tags: ["minimalist", "personalized", "name"],
    },
    // --- Additional 30 Trendy Products ---
    // T-Shirts (5)
    {
      name: "Abstract Splash Art Tee",
      slug: "abstract-splash-art-tee",
      description: "Express your creativity with this vibrant abstract splash art T-shirt. A unique piece for the modern artist.",
      price: "750",
      discountPrice: "649",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_abstract.png",
      featured: true,
      customizable: true,
      tags: ["art", "abstract", "vibrant"],
    },
    {
      name: "Cyberpunk Dhaka City Tee",
      slug: "cyberpunk-dhaka-city-tee",
      description: "Dhaka meets the future. A stunning cyberpunk-inspired illustration of the city skyline on a premium black T-shirt.",
      price: "799",
      discountPrice: "699",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_retro.png",
      featured: true,
      customizable: true,
      tags: ["dhaka", "cyberpunk", "future"],
    },
    {
      name: "Retro Gaming Controller Tee",
      slug: "retro-gaming-controller-tee",
      description: "For the old-school gamers. Features a classic 8-bit controller design for a nostalgic trip back to the 90s.",
      price: "699",
      discountPrice: "599",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_gaming.png",
      featured: false,
      customizable: true,
      tags: ["gaming", "retro", "8bit"],
    },
    {
      name: "Minimalist Nature Leaf Tee",
      slug: "minimalist-nature-leaf-tee",
      description: "Simple, clean, and elegant. A single leaf line drawing on a premium organic cotton base.",
      price: "699",
      discountPrice: "599",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_floral.png",
      featured: false,
      customizable: true,
      tags: ["nature", "minimalist", "organic"],
    },
    {
      name: "Cute Panda Hug Tee",
      slug: "cute-panda-hug-tee",
      description: "Spread the love with this adorable panda hug illustration. Soft, comfortable, and guaranteed to make you smile.",
      price: "750",
      discountPrice: "649",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_space.png",
      featured: true,
      customizable: true,
      tags: ["panda", "cute", "love"],
    },
    // Hoodies (5)
    {
      name: "Galactic Nebula Fleece Hoodie",
      slug: "galactic-nebula-fleece-hoodie",
      description: "Wrap yourself in the stars. A high-resolution nebula print on a premium heavy fleece hoodie.",
      price: "1799",
      discountPrice: "1599",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_explore.png",
      featured: true,
      customizable: true,
      tags: ["galaxy", "space", "fleece"],
    },
    {
      name: "Vintage Varsity Letter Hoodie",
      slug: "vintage-varsity-letter-hoodie",
      description: "Classic campus style. Features a bold varsity letter patch and a comfortable, relaxed fit.",
      price: "1699",
      discountPrice: "1499",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_essential.png",
      featured: false,
      customizable: true,
      tags: ["varsity", "vintage", "campus"],
    },
    {
      name: "Minimalist Wave Line Art Hoodie",
      slug: "minimalist-wave-line-art-hoodie",
      description: "Inspired by the ocean. A continuous line drawing of a wave for a calm, sophisticated look.",
      price: "1599",
      discountPrice: "1399",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_abstract.png",
      featured: true,
      customizable: true,
      tags: ["ocean", "minimalist", "art"],
    },
    {
      name: "Retro Synthwave Sun Hoodie",
      slug: "retro-synthwave-sun-hoodie",
      description: "80s vibes all the way. A vibrant synthwave sun design on a premium charcoal hoodie.",
      price: "1699",
      discountPrice: "1499",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_retro.png",
      featured: true,
      customizable: true,
      tags: ["80s", "synthwave", "retro"],
    },
    {
      name: "Cozy Oversized Cloud Hoodie",
      slug: "cozy-oversized-cloud-hoodie",
      description: "Like wearing a cloud. Super soft, oversized fit for the ultimate lounging experience.",
      price: "1899",
      discountPrice: "1699",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_love.png",
      featured: false,
      customizable: true,
      tags: ["cozy", "oversized", "soft"],
    },
    // Mugs (5)
    {
      name: "Boss Lady Floral Mug",
      slug: "boss-lady-floral-mug",
      description: "For the women who lead. Elegant floral design with bold 'Boss Lady' typography.",
      price: "550",
      discountPrice: "449",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_plant.png",
      featured: true,
      customizable: true,
      tags: ["boss", "floral", "gift"],
    },
    {
      name: "Programmer Code Fuel Mug",
      slug: "programmer-code-fuel-mug",
      description: "Turn coffee into code. Features a 'Code Fuel' message and a syntax-highlighted code snippet.",
      price: "499",
      discountPrice: "399",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_initial.png",
      featured: true,
      customizable: true,
      tags: ["programming", "code", "coffee"],
    },
    {
      name: "Minimalist Mountain Peak Mug",
      slug: "minimalist-mountain-peak-mug",
      description: "For the explorers. A simple mountain peak silhouette on a clean white ceramic base.",
      price: "450",
      discountPrice: "349",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_love.png",
      featured: false,
      customizable: true,
      tags: ["mountain", "minimalist", "adventure"],
    },
    {
      name: "Retro Pixel Heart Mug",
      slug: "retro-pixel-heart-mug",
      description: "Show your love in 8-bit. A classic red pixel heart design for a nostalgic touch.",
      price: "450",
      discountPrice: "349",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_birthday.png",
      featured: true,
      customizable: true,
      tags: ["love", "retro", "pixel"],
    },
    {
      name: "Cute Shiba Inu Mug",
      slug: "cute-shiba-inu-mug",
      description: "Much wow. Very coffee. An adorable Shiba Inu illustration to brighten your morning.",
      price: "550",
      discountPrice: "449",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_abstract.png",
      featured: true,
      customizable: true,
      tags: ["shiba", "cute", "dog"],
    },
    // Caps (5)
    {
      name: "Vintage Denim Dad Hat",
      slug: "vintage-denim-dad-hat",
      description: "Effortlessly cool. Premium washed denim for a perfectly worn-in look and feel.",
      price: "899",
      discountPrice: "749",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_travel.png",
      featured: true,
      customizable: true,
      tags: ["denim", "vintage", "cool"],
    },
    {
      name: "Modern Mesh Trucker Cap",
      slug: "modern-mesh-trucker-cap",
      description: "Stay cool and stylish. Features a breathable mesh back and a sleek front panel design.",
      price: "799",
      discountPrice: "649",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_gaming.png",
      featured: false,
      customizable: true,
      tags: ["trucker", "modern", "breathable"],
    },
    {
      name: "Minimalist Peak Snapback",
      slug: "minimalist-peak-snapback",
      description: "Clean and sharp. A minimalist snapback with a focus on quality and fit.",
      price: "850",
      discountPrice: "699",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_space.png",
      featured: true,
      customizable: true,
      tags: ["minimalist", "snapback", "sharp"],
    },
    {
      name: "Retro Stripe Baseball Cap",
      slug: "retro-stripe-baseball-cap",
      description: "Classic athletic style. Features retro stripes and a comfortable cotton construction.",
      price: "750",
      discountPrice: "599",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_floral.png",
      featured: false,
      customizable: true,
      tags: ["retro", "baseball", "athletic"],
    },
    {
      name: "Tactical Outdoor Performance Cap",
      slug: "tactical-outdoor-performance-cap",
      description: "Built for the elements. Water-resistant fabric and a secure fit for all your adventures.",
      price: "999",
      discountPrice: "849",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_hairday.png",
      featured: true,
      customizable: true,
      tags: ["tactical", "outdoor", "performance"],
    },
    // Long Sleeves (5)
    {
      name: "Artistic Brush Stroke Long Sleeve",
      slug: "artistic-brush-stroke-long-sleeve",
      description: "A wearable canvas. Features bold, hand-painted brush strokes for a truly unique look.",
      price: "999",
      discountPrice: "849",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_artistic.png",
      featured: true,
      customizable: true,
      tags: ["art", "brushstroke", "unique"],
    },
    {
      name: "Vintage Map Explorer Long Sleeve",
      slug: "vintage-map-explorer-long-sleeve",
      description: "For the world travelers. Features a beautiful vintage map illustration across the chest.",
      price: "950",
      discountPrice: "799",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_nature.png",
      featured: true,
      customizable: true,
      tags: ["travel", "map", "explorer"],
    },
    {
      name: "Minimalist Stripe Sleeve Long Sleeve",
      slug: "minimalist-stripe-sleeve-long-sleeve",
      description: "Clean and modern. Features subtle stripes on the sleeves for a sophisticated touch.",
      price: "899",
      discountPrice: "749",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_typographic.png",
      featured: false,
      customizable: true,
      tags: ["minimalist", "stripe", "modern"],
    },
    {
      name: "Retro 80s Grid Long Sleeve",
      slug: "retro-80s-grid-long-sleeve",
      description: "Back to the future. A vibrant 80s grid design for a bold, nostalgic statement.",
      price: "950",
      discountPrice: "799",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_retro80s.png",
      featured: true,
      customizable: true,
      tags: ["80s", "grid", "retro"],
    },
    {
      name: "Cozy Waffle Knit Long Sleeve",
      slug: "cozy-waffle-knit-long-sleeve",
      description: "The ultimate layering piece. Soft waffle knit fabric for warmth and texture.",
      price: "1099",
      discountPrice: "899",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_initial.png",
      featured: false,
      customizable: true,
      tags: ["cozy", "waffle", "texture"],
    },
    // Water Bottles (5)
    {
      name: "Sleek Matte Black Flask",
      slug: "sleek-matte-black-flask",
      description: "Sophisticated and stealthy. A premium matte black finish on a double-walled insulated flask.",
      price: "1350",
      discountPrice: "1099",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_retro.png",
      featured: true,
      customizable: true,
      tags: ["matte", "black", "flask"],
    },
    {
      name: "Vibrant Ombre Sport Bottle",
      slug: "vibrant-ombre-sport-bottle",
      description: "Add a splash of color to your workout. A beautiful ombre finish on a lightweight aluminum bottle.",
      price: "899",
      discountPrice: "749",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_floral.png",
      featured: true,
      customizable: true,
      tags: ["ombre", "sport", "vibrant"],
    },
    {
      name: "Minimalist Clear Glass Bottle",
      slug: "minimalist-clear-glass-bottle",
      description: "Pure and clean. High-quality borosilicate glass with a protective silicone sleeve.",
      price: "1150",
      discountPrice: "899",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_initial.png",
      featured: false,
      customizable: true,
      tags: ["glass", "minimalist", "clean"],
    },
    {
      name: "Retro 8-Bit Heart Bottle",
      slug: "retro-8-bit-heart-bottle",
      description: "Level up your hydration. A classic red pixel heart design for the gaming enthusiast.",
      price: "950",
      discountPrice: "799",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_gaming.png",
      featured: true,
      customizable: true,
      tags: ["pixel", "heart", "gaming"],
    },
    {
      name: "Tactical Military Grade Canteen",
      slug: "tactical-military-grade-canteen",
      description: "Built to survive anything. A heavy-duty canteen with a rugged finish and a secure cap.",
      price: "1450",
      discountPrice: "1199",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_fitness.png",
      featured: true,
      customizable: true,
      tags: ["tactical", "canteen", "rugged"],
    },
  ];

  console.log(`Found ${products.length} trendy products to process.`);

  for (const product of products) {
    const existing = await db.select().from(productsTable).where(eq(productsTable.slug, product.slug));
    if (existing.length === 0) {
      await db.insert(productsTable).values({
        ...product,
        images: [product.imageUrl],
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["White", "Black", "Navy", "Grey"],
        stock: 100,
        rating: "4.9",
        reviewCount: Math.floor(Math.random() * 50) + 10,
        updatedAt: new Date(),
      } as any);
      console.log(`Inserted product: ${product.name}`);
    }
  }

  console.log("Trendy product insertion complete!");
  process.exit(0);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
