import { Router, type IRouter } from "express";
import healthRouter from "./health";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import ordersRouter from "./orders";
import settingsRouter from "./settings";
import adminRouter from "./admin";
import authRouter from "./auth";
import blogRouter from "./blog";
import storageRouter from "./storage";
import backupRouter from "./backup";
import facebookRouter from "./facebook";
import promoCodesRouter from "./promoCodes";
import reviewsRouter from "./reviews";
import referralsRouter from "./referrals";
import sitemapRouter from "./sitemap";
import publicStatsRouter from "./publicStats";
import removeBgRouter from "./removeBg";
import testimonialsRouter from "./testimonials";
import deploymentRouter from "./deployment";
import hampersRouter from "./hampers";
import abandonedCartRouter from "./abandonedCart";
import activityLogRouter from "./activityLog";
import seoRouter from "./seo";
import newsletterRouter from "./newsletter";
import aiRouter from "./ai";
import aiExecuteRouter from "./aiExecute";
import draftsRouter from "./drafts";
import telegramWebhookRouter from "./telegramWebhook";
import uptimeRobotRouter from "./uptimeRobot";
import dbClusterRouter from "./dbCluster";
import orderMessagesRouter from "./orderMessages";
import notificationsRouter from "./notifications";
import mockupsRouter from "./mockups";
import mockupRenderRouter from "./mockupRender";
import systemHealthRouter from "./systemHealth";
import secretsRouter from "./secrets";

const router: IRouter = Router();

router.use(healthRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(ordersRouter);
router.use(settingsRouter);
router.use(adminRouter);
router.use(authRouter);
router.use(blogRouter);
router.use(storageRouter);
router.use(backupRouter);
router.use(facebookRouter);
router.use(promoCodesRouter);
router.use(reviewsRouter);
router.use(referralsRouter);
router.use(sitemapRouter);
router.use(publicStatsRouter);
router.use(removeBgRouter);
router.use(testimonialsRouter);
router.use(deploymentRouter);
router.use(hampersRouter);
router.use(abandonedCartRouter);
router.use(activityLogRouter);
router.use(seoRouter);
router.use(newsletterRouter);
router.use(aiRouter);
router.use(aiExecuteRouter);
router.use(draftsRouter);
router.use(telegramWebhookRouter);
router.use(uptimeRobotRouter);
router.use(dbClusterRouter);
router.use(orderMessagesRouter);
router.use(notificationsRouter);
router.use(mockupsRouter);
router.use(mockupRenderRouter);
router.use(systemHealthRouter);
router.use(secretsRouter);

export default router;
