export * from "./generated/api";
export * from "./generated/api.schemas";
export { setBaseUrl, setAuthTokenGetter } from "./custom-fetch";
export type { AuthTokenGetter } from "./custom-fetch";

export type {
  Testimonial,
  OrderItem,
  AdminCustomer,
  AdminStatsWeeklyDataItem,
  AdminStatsPaymentDistributionItem,
  CreateOrderRequest,
  CreateProductRequest,
  UpdateProductRequest,
  Review,
  BlogPostInput,
  DesignerSettings,
  FacebookPost,
  FetchSocialUrl200Post,
  BlogSettings,
  AdminGuestCustomer,
} from "./trynex-hooks";

export {
  CreateOrderRequestPaymentMethod,
  UpdateOrderStatusRequestStatus,
  useToggleProductFeatured,
  useCreateCategory,
  useUpdateCategory,
  useDeleteCategory,
  useGetTestimonials,
  useAdminListTestimonials,
  useCreateTestimonial,
  useUpdateTestimonial,
  useDeleteTestimonial,
  useUpdateOrderStatus,
  useUpdatePaymentStatus,
  useAdminMe,
  useListAdminCustomers,
  useListAdminGuestCustomers,
  useConvertGuestCustomer,
  useDeleteGuestCustomer,
  getExportBackupUrl,
  getExportOrdersCsvUrl,
  useImportBackup,
  useGetDesignerSettings,
  usePatchDesignerSettings,
  useListAdminReviews,
  useApproveReview,
  useDeleteReview,
  useCreateBlogPost,
  useUpdateBlogPost,
  useDeleteBlogPost,
  usePatchBlogSettings,
  useFetchFacebookPosts,
  useFetchSocialUrl,
  useImportFacebookProduct,
} from "./trynex-hooks";
