import { useEffect } from "react";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { SEOHead } from "@/components/SEOHead";

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div className="mb-8 print:mb-6 break-inside-avoid">
    <h2 className="text-xl font-black text-gray-900 mb-3 pb-2 border-b-2 border-orange-400">{title}</h2>
    <div className="space-y-2 text-gray-700 text-sm leading-relaxed">{children}</div>
  </div>
);

const Step = ({ n, children }: { n: number; children: React.ReactNode }) => (
  <div className="flex gap-3 items-start">
    <div className="w-7 h-7 rounded-full bg-orange-500 text-white text-xs font-black flex items-center justify-center shrink-0 mt-0.5">{n}</div>
    <div className="flex-1">{children}</div>
  </div>
);

const Tip = ({ icon, children }: { icon: string; children: React.ReactNode }) => (
  <div className="flex gap-2 items-start p-3 rounded-xl bg-orange-50 border border-orange-100">
    <span className="text-base">{icon}</span>
    <span className="text-sm text-gray-700">{children}</span>
  </div>
);

const Tag = ({ children }: { children: React.ReactNode }) => (
  <code className="px-1.5 py-0.5 rounded text-xs font-mono bg-gray-100 text-gray-800 border border-gray-200">{children}</code>
);

export function SeoGuide() {
  useEffect(() => {
    document.title = "SEO Guide – TryNex Lifestyle";
  }, []);

  return (
    <>
      <SEOHead
        title="SEO & Google Ranking Guide — TryNex Lifestyle"
        description="Complete SEO setup guide for TryNex Lifestyle: Google Search Console, indexing, keyword strategy, AI platform ranking, and performance tips."
        noindex
      />
      <div className="print:hidden">
        <Navbar />
      </div>

      <div className="max-w-3xl mx-auto px-4 py-8 print:py-4 print:px-0">

        {/* Header */}
        <div className="text-center mb-10 print:mb-6">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full text-sm font-bold text-white mb-4"
            style={{ background: "linear-gradient(135deg,#E85D04,#FB8500)" }}>
            TryNex Lifestyle · SEO Action Guide
          </div>
          <h1 className="text-3xl font-black text-gray-900 mb-2">
            🔍 SEO & Google Ranking Guide
          </h1>
          <p className="text-gray-500 text-sm">Step-by-step setup for TryNex · Custom Apparel Bangladesh</p>
          <button
            onClick={() => window.print()}
            className="mt-4 print:hidden px-5 py-2 rounded-xl text-sm font-bold text-white"
            style={{ background: "linear-gradient(135deg,#E85D04,#FB8500)" }}
          >
            🖨️ Save as PDF / Print
          </button>
        </div>

        {/* Google Search Console */}
        <Section title="1. Google Search Console Setup">
          <div className="space-y-3">
            <Step n={1}>
              Go to <strong>search.google.com/search-console</strong> and click <strong>Start Now</strong>.
            </Step>
            <Step n={2}>
              Choose <strong>URL prefix</strong> property type. Enter your domain: <Tag>https://trynexshop.com</Tag>
            </Step>
            <Step n={3}>
              Verify ownership via <strong>HTML meta tag</strong> method. Copy the meta tag and ask your dev to add it to the <Tag>&lt;head&gt;</Tag> of your site, or add it in the admin Settings → SEO section.
            </Step>
            <Step n={4}>
              After verification, submit your sitemap: <Tag>/sitemap.xml</Tag> is already generated by TryNex — submit it in <strong>Sitemaps</strong> section.
            </Step>
            <Tip icon="✅">TryNex already generates a dynamic sitemap at <Tag>/sitemap.xml</Tag> — includes all products, blog posts, and categories automatically.</Tip>
          </div>
        </Section>

        {/* Google My Business */}
        <Section title="2. Google Business Profile (Local SEO)">
          <div className="space-y-3">
            <Step n={1}>Go to <strong>business.google.com</strong> and create a free business profile.</Step>
            <Step n={2}>Business name: <strong>TryNex Lifestyle</strong> · Category: <strong>Clothing Store / Custom T-Shirt Store</strong></Step>
            <Step n={3}>Add your Dhaka address, phone number (+88019...), WhatsApp link, and website URL.</Step>
            <Step n={4}>Upload 5–10 product photos. Listings with photos get 35% more clicks.</Step>
            <Step n={5}>Ask every customer (via WhatsApp follow-up) to leave a 5-star Google review.</Step>
            <Tip icon="⭐">Google reviews are the #1 local ranking factor. 10+ reviews puts you on the map literally.</Tip>
          </div>
        </Section>

        {/* On-Page SEO */}
        <Section title="3. On-Page SEO — Product Pages">
          <div className="space-y-3">
            <Tip icon="🎯">Target keywords: <strong>custom t-shirt Bangladesh</strong>, <strong>custom hoodie Dhaka</strong>, <strong>print on demand Bangladesh</strong>, <strong>TryNex custom apparel</strong></Tip>
            <Step n={1}><strong>Product titles</strong> — Include keyword + size/material. E.g.: <em>Custom Print Unisex T-Shirt – 230GSM Cotton – Bangladesh</em></Step>
            <Step n={2}><strong>Product descriptions</strong> — Write 100–200 words per product. Mention fabric, GSM, printing method, delivery area.</Step>
            <Step n={3}><strong>Image alt text</strong> — Every product image should have descriptive alt text. E.g.: <em>White custom hoodie front view 320GSM Dhaka Bangladesh</em></Step>
            <Step n={4}><strong>URL slugs</strong> — Keep them clean: <Tag>/products/custom-unisex-tshirt</Tag> not <Tag>/products/product-123</Tag></Step>
            <Step n={5}><strong>Blog content</strong> — Publish 2 articles/month targeting long-tail keywords like <em>"best custom t-shirt shop in Dhaka"</em></Step>
          </div>
        </Section>

        {/* Technical SEO */}
        <Section title="4. Technical SEO Checklist">
          <div className="grid grid-cols-2 gap-2 print:grid-cols-2">
            {[
              ["✅ Done", "Dynamic sitemap at /sitemap.xml"],
              ["✅ Done", "Mobile-responsive design"],
              ["✅ Done", "Fast Vite/React build"],
              ["✅ Done", "SEO meta tags on all pages"],
              ["🔧 Do this", "Add Google Analytics 4 (GA4)"],
              ["🔧 Do this", "Set up Clarity (free heatmaps)"],
              ["🔧 Do this", "Verify site speed < 3s (PageSpeed Insights)"],
              ["🔧 Do this", "Add structured data (Product schema)"],
              ["🔧 Do this", "Set up 301 redirects for old URLs"],
              ["🔧 Do this", "Enable Gzip/Brotli compression on server"],
            ].map(([status, item]) => (
              <div key={item} className="flex gap-2 items-start text-sm p-2 rounded-lg bg-gray-50">
                <span className="font-bold text-xs">{status}</span>
                <span className="text-gray-600">{item}</span>
              </div>
            ))}
          </div>
        </Section>

        {/* Google Analytics */}
        <Section title="5. Google Analytics 4 (GA4) Setup">
          <div className="space-y-3">
            <Step n={1}>Go to <strong>analytics.google.com</strong> → create account → create GA4 property.</Step>
            <Step n={2}>Get your Measurement ID: <Tag>G-XXXXXXXXXX</Tag></Step>
            <Step n={3}>In TryNex Admin → Settings → add the GA4 Measurement ID to enable tracking automatically.</Step>
            <Step n={4}>In Google Analytics, set up a Conversion event for <strong>purchase</strong> to track sales.</Step>
            <Tip icon="📊">Connect GA4 to Google Search Console for combined search + behavior data in one dashboard.</Tip>
          </div>
        </Section>

        {/* Keyword Strategy */}
        <Section title="6. Bangladesh E-Commerce Keyword Strategy">
          <div className="space-y-2">
            <p><strong>High priority keywords to target:</strong></p>
            <div className="grid grid-cols-2 gap-1.5 print:grid-cols-2">
              {[
                "custom t-shirt Bangladesh",
                "custom hoodie Dhaka",
                "print on demand BD",
                "কাস্টম টি-শার্ট ঢাকা",
                "gift hamper Bangladesh",
                "custom mug printing BD",
                "corporate t-shirt order",
                "sublimation print Dhaka",
                "custom cap printing BD",
                "water bottle printing Dhaka",
              ].map(kw => (
                <div key={kw} className="px-2 py-1 rounded-lg bg-blue-50 border border-blue-100 text-xs font-medium text-blue-800">{kw}</div>
              ))}
            </div>
            <Tip icon="🔍">Use <strong>Google Keyword Planner</strong> (free with Google Ads account) to find exact monthly search volumes for Bangladesh.</Tip>
          </div>
        </Section>

        {/* AI Platform Ranking */}
        <Section title="7. AI Search Platforms (ChatGPT, Perplexity, Gemini)">
          <div className="space-y-3">
            <p className="text-sm text-gray-600">AI chatbots now answer shopping queries. To rank in AI results:</p>
            <Step n={1}><strong>Get mentions</strong> — Ask satisfied customers to post reviews mentioning TryNex on Google, Facebook, Trustpilot. AI pulls from review sites.</Step>
            <Step n={2}><strong>Write authoritative blog content</strong> — Articles like <em>"Best Custom T-Shirt Shops in Bangladesh 2025"</em> that rank on Google also get cited by AI.</Step>
            <Step n={3}><strong>Add structured data</strong> — Add <Tag>Organization</Tag>, <Tag>LocalBusiness</Tag>, and <Tag>Product</Tag> schema JSON-LD to your pages.</Step>
            <Step n={4}><strong>Wikipedia / Wikidata</strong> — If TryNex becomes well-known enough, create a Wikipedia/Wikidata entry. AI heavily cites these.</Step>
            <Step n={5}><strong>Be on aggregators</strong> — List on Bikroy, Daraz, Facebook Shop, Shajgoj. AI discovers brands from multiple data points.</Step>
            <Tip icon="🤖">ChatGPT/Perplexity answers from the live web. Every high-ranking Google result for your keywords becomes an AI citation source.</Tip>
          </div>
        </Section>

        {/* Backlinks */}
        <Section title="8. Backlink Building (Bangladesh)">
          <div className="space-y-3">
            <Step n={1}><strong>Facebook Groups</strong> — Share product posts in BD Business, Startup Bangladesh, Fashion BD groups. Links from Facebook count.</Step>
            <Step n={2}><strong>Blog partnerships</strong> — Reach out to lifestyle bloggers in Dhaka for sponsored reviews with a link back to TryNex.</Step>
            <Step n={3}><strong>Press / News</strong> — Submit to Prothom Alo Tech section, TechShohor, or Daily Star feature stories about custom printing.</Step>
            <Step n={4}><strong>Business directories</strong> — List on Bikroy Business, Yellow Pages BD, Bangladesh B2B portals.</Step>
            <Step n={5}><strong>YouTube</strong> — Create unboxing / process videos. YouTube ranks on Google and video backlinks count.</Step>
          </div>
        </Section>

        {/* Monthly Action Plan */}
        <Section title="9. Monthly SEO Action Plan">
          <div className="space-y-2">
            {[
              ["Month 1", "Setup: Search Console, GA4, sitemap submission, fix all technical issues"],
              ["Month 2", "Content: Write 4 blog posts targeting high-volume keywords"],
              ["Month 3", "Reviews: Collect 20+ Google reviews, list on 5 directories"],
              ["Month 4", "Backlinks: 3 blog partnership mentions, 2 press mentions"],
              ["Month 5", "Optimization: Fix pages with high bounce rate from GA4 data"],
              ["Month 6", "Scale: Identify top-performing pages, invest more content there"],
            ].map(([month, action]) => (
              <div key={month} className="flex gap-3 items-start p-2.5 rounded-xl border border-gray-100">
                <span className="font-black text-orange-500 text-xs whitespace-nowrap">{month}</span>
                <span className="text-sm text-gray-600">{action}</span>
              </div>
            ))}
          </div>
        </Section>

        {/* Quick wins */}
        <Section title="10. Quick Wins (Do This Week)">
          <div className="space-y-2">
            {[
              "Submit sitemap to Google Search Console",
              "Create Google Business Profile",
              "Add GA4 tracking ID in admin settings",
              "Share 3 product posts in Facebook BD groups with website link",
              "Ask last 10 customers to leave a Google review via WhatsApp",
              "Add your site to Bikroy.com free listing",
              "Check PageSpeed score — aim for 80+ on mobile",
            ].map((win, i) => (
              <div key={i} className="flex gap-2 items-center text-sm">
                <span className="w-5 h-5 rounded-full bg-green-100 text-green-700 text-xs flex items-center justify-center font-bold shrink-0">✓</span>
                <span>{win}</span>
              </div>
            ))}
          </div>
        </Section>

        {/* Footer */}
        <div className="mt-10 p-4 rounded-2xl text-center print:mt-6" style={{ background: "linear-gradient(135deg,#fff4ee,#ffe8d4)", border: "1px solid #fed7aa" }}>
          <p className="text-sm font-bold text-orange-700">TryNex Lifestyle SEO Guide</p>
          <p className="text-xs text-orange-500">trynex.app · Custom Apparel Bangladesh · WhatsApp: 01903426915</p>
          <p className="text-xs text-gray-400 mt-1">Generated {new Date().toLocaleDateString("en-BD", { year: "numeric", month: "long", day: "numeric" })}</p>
        </div>
      </div>

      <div className="print:hidden">
        <Footer />
      </div>
    </>
  );
}
